---
$schema: "http://json-schema.org/draft-04/schema"
#$schema: "http://stsci.edu/schemas/yaml-schema/draft-01"
title: Exercise schema
type: object
required:
  - title
  - description
  - instructions
  - view_type
  - files
  - container
optional:
  - radar_info

definitions:
  languageType:
    type: string
    enum:
      - python
      - scala
      - javascript

additionalProperties: false
properties:
  title:
    description: The name of the exercise
    type: string
  description:
    type: string
  instructions:
    type: string
  view_type:
    type: string
  files:
    type: array
    items:
      type: object
      required:
        - field
      properties:
        field:
          type: string
        name:
          type: string
  container:
    type: object
    properties:
      image:
        type: string
      mount:
        type: string
      cmd:
        type: string
  radar_info:
    type: object
    required:
      - tokenizer
    properties:
      tokenizer:
        $ref: '#/definitions/languageType'
        #enum:
        #  - python
        #  - scala
        #  - javascript
      minimum_match_tokens:
        type: number
        minimum: 0
